### ISSUE TITLE
LeetCode 209 - Minimum Size Subarray Sum

### ISSUE THREAD

**Issue by harishkadamudi** [sherigar/HacktoberFest-2023#176]
Given an array of positive integers nums and a positive integer target, return the minimal length of a 
subarray whose sum is greater than or equal to target. If there is no such subarray, return 0 instead.
Would like to implement it in Go
HACTOBERFEST2023
@sherigar

**Comment by Pritee-gupta-jpg** [comment]
please assign it to me

**Comment by harishkadamudi** [comment]
@sherigar - PR - https://github.com/sherigar/HacktoberFest-2023/pull/188
