### ISSUE TITLE
DIFFERENT METHODS OF SWAPPING IN C++

### ISSUE THREAD

**Issue by talha-ansarii** [sherigar/HacktoberFest-2023#57]
I want to write code to your repo in which i will show different methods of swapping of two numbers
@sherigar please assign me this issue under hacktoberfest

**Comment by sherigar** [comment]
ok

**Comment by AkashKMathew** [comment]
Hey, I would like to contribute to this project. I have been coding using C++ for a long time. So I can show different methods to swap two numbers easily. Please assign this to me.

**Comment by sanketsur22** [comment]
I have a broad knowledge of coding and can use C++ to demonstrate three alternative methods of swapping. 
Please assign this problem to me, @sherigar.

**Comment by srusti610** [comment]
Hello sir I can contribute to this issue kinldy assign

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under hacktoberfest23.
