### ISSUE TITLE
Pattern Double Sided Arrow in C++

### ISSUE THREAD

**Issue by talha-ansarii** [sherigar/HacktoberFest-2023#58]
I want to solve this pattern problem 

                              1 
                        2 1   1 2 
                    3 2 1       1 2 3 
                4 3 2 1           1 2 3 4 
                    3 2 1       1 2 3 
                        2 1   1 2 
                            1

Please assign this issue under hacktober fest

**Comment by talha-ansarii** [comment]
@sherigar

**Comment by Shankar009378** [comment]
hi sir i can solve that please assign me

**Comment by sherigar** [comment]
ok

**Comment by Pradyumn04** [comment]
Kindly allow me to solve this issue and provide the hacktober fest tag
