### ISSUE TITLE
Flame in python

### ISSUE THREAD

**Issue by Vivekumar08** [sherigar/HacktoberFest-2023#81]
add a program for FLAME in python

**Comment by Vivekumar08** [comment]
Please assign me this issue, I raised the P.R

**Comment by Vivekumar08** [comment]
Please review this P.R, give some suggestions and feedback
[https://github.com/sherigar/HacktoberFest-2023/pull/80]

**Comment by Vivekumar08** [comment]
Hii, @sherigar, why my PR is excluded 
![image](https://github.com/sherigar/HacktoberFest-2023/assets/78597373/5112f50a-a8d2-4f54-afa1-4fb230365b27)

**Comment by janhavibagret** [comment]
Can you please assign me this issue? I would like to work on it.
